### ISSUE TITLE
apres l'installation

### ISSUE THREAD

**Issue by seblang** [jeedom/synology#1]
bonjour suite a l'install mon RFX com fonctionne bien mais les clef swave UZB1 non..........impossible a detecteur j'ai installé SynoZwave  mais rien a faire!  je ne sais pas comment installer le synology_openzwave.patch . merci de votre aide (vera3seblang@gmail.com) (j'ai un ds214 play)

**Comment by zoic21** [comment]
Bonjour,
Peux tu poster sur le forum plutôt ? Ce dépôt ne sert plus et sera bientôt supprimé.

**Comment by seblang** [comment]
Hello merci du retour déjà.... Forum jeedom ou synology ?  Tu as un lien
stp ?  Seb

**Comment by zoic21** [comment]
Forum jeedom : https://jeedom.com/forum
